pipeline {
    agent any
    stages {
        stage('Build') {
            step {
                sh '''
                docker build -t eugil/flask-app /Task1
                docker build -f Dockerfile_nginx -t eugil/custom-nginx /Task1
                '''
            }
        }
        stage('Test') {
            echo "Testing"
        }
        stage('Deploy') {

        }
    }
}