pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                docker build -t eugil/flask-app ./Task1
                docker build -f Dockerfile_nginx -t eugil/custom-nginx /Task1
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying"
            }
        }
    }
}